#!/bin/bash

for BINS in `seq 1 20`; do

    java -cp weka.jar:. weka.filters.unsupervised.attribute.Discretize -b -i input/dataset_80_train.arff -o output/ej.4/train_`printf %02d "$BINS"`_bins.igual.ancho.arff -r input/dataset_20_test.arff -s output/ej.4/test_`printf %02d "$BINS"`_bins.igual.ancho.arff -B "$BINS" -M -1.0 -R first-last

    java -cp weka.jar:. weka.filters.unsupervised.attribute.Discretize -b -i input/dataset_80_train.arff -o output/ej.4/train_`printf %02d "$BINS"`_bins.igual.frecuencia.arff -r input/dataset_20_test.arff -s output/ej.4/test_`printf %02d "$BINS"`_bins.igual.frecuencia.arff -F -B "$BINS" -M -1.0 -R first-last

    java -cp weka.jar:. weka.filters.supervised.attribute.Discretize -b -i input/dataset_80_train.arff -o output/ej.4/train_`printf %02d "$BINS"`_bins.supervisado.arff -r input/dataset_20_test.arff -s output/ej.4/test_`printf %02d "$BINS"`_bins.supervisado.arff -R first-last -c 13

    echo "done for $BINS bins"
    
done
