#!/usr/bin/env python
import sys
from random import randint

with open(sys.argv[1], 'r') as f:
    for line in f.readlines():
        (start, end) = line.strip().split('-')
        start = int(start)
        if end == '00': 
            end = int(90)
        else:
            end = int(end)
        age = randint(start, end)
        print("%d" % age)
