#!/bin/bash

for BINS in `seq 1 20`; do

    BB=`printf %02d $BINS`
    echo "processing dataset with ${BB} bins"

    for CONFIDENCE_FACTOR in 0.025 0.05 0.075 0.1 0.125 0.150 0.175 0.2 0.225 0.25 0.275 0.3 0.325 0.350 0.375 0.4 0.425 0.45 0.475 0.5; do

	java -Xmx1024m -cp ./weka.jar:. weka.classifiers.trees.J48 -t output/ej.4/train_${BB}_bins.igual.ancho.arff      -T output/ej.4/test_${BB}_bins.igual.ancho.arff      -C ${CONFIDENCE_FACTOR} -M 2 > output/ej.4/ej4.${CONFIDENCE_FACTOR}.${BB}.igual.ancho.out ;
	java -Xmx1024m -cp ./weka.jar:. weka.classifiers.trees.J48 -t output/ej.4/train_${BB}_bins.igual.frecuencia.arff -T output/ej.4/test_${BB}_bins.igual.frecuencia.arff -C ${CONFIDENCE_FACTOR} -M 2 > output/ej.4/ej4.${CONFIDENCE_FACTOR}.${BB}.igual.frecuencia.out ;
	java -Xmx1024m -cp ./weka.jar:. weka.classifiers.trees.J48 -t output/ej.4/train_${BB}_bins.supervisado.arff      -T output/ej.4/test_${BB}_bins.supervisado.arff      -C ${CONFIDENCE_FACTOR} -M 2 > output/ej.4/ej4.${CONFIDENCE_FACTOR}.${BB}.supervisado.out ;

	echo "done $CONFIDENCE_FACTOR" ;
    
    done

done
