#!/usr/bin/env python
import os, csv, random, sys
from collections import Counter
import itertools

# uso:
# ./split_validation_and_test_sets [archivo]
#
# ejemplo:
# ./split_validation_and_test_sets input/dataset.csv

input_data_file = sys.argv[1]

with open(input_data_file, 'r') as csvfile:
    freader = csv.reader(csvfile, delimiter=',', quotechar='"')
    records = [record for record in freader]
    (field_names, records) = (records[0], records[1:])
    record_indices = range(0, len(records))
    number_of_records_to_keep = int(0.20 * len(records))
    indices_to_keep = random.sample(record_indices, number_of_records_to_keep)
    validation_records = [r for (index, r) in enumerate(records) if (index in indices_to_keep)]
    test_records = [r for (index, r) in enumerate(records) if (index not in indices_to_keep)]
    
    output_data_file = 'validation_dataset.csv'
    with open(output_data_file, 'w') as csvfile:
        fwriter = csv.writer(csvfile, delimiter=',')
        fwriter.writerow(field_names)
        fwriter.writerows(validation_records)
    print("%s: done" % output_data_file)

    output_data_file = 'test_dataset.csv'
    with open(output_data_file, 'w') as csvfile:
        fwriter = csv.writer(csvfile, delimiter=',')
        fwriter.writerow(field_names)
        fwriter.writerows(test_records)
    print("%s: done" % output_data_file)
